name: Check PR & Commits Naming Convention

on:
  pull_request:
    types: [ opened, synchronize, edited ]

jobs:
  check-conventions:
    runs-on: ubuntu-latest
    steps:
    - name: "🛂 Check PR & Commits Naming Convention"
      uses: DevOpsActions/naming-conventions@main
      if: github.actor != 'dependabot[bot]'
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
